export const demoCategories = [
  { id: 'cat-1', name: 'Modul Ajar', slug: 'modul-ajar', color: '#0ea5a0', sort_order: 1 },
  { id: 'cat-2', name: 'ATP', slug: 'atp', color: '#8b5cf6', sort_order: 2 },
  { id: 'cat-3', name: 'Media Pembelajaran', slug: 'media-pembelajaran', color: '#f59e0b', sort_order: 3 },
  { id: 'cat-4', name: 'Administrasi', slug: 'administrasi', color: '#ef4444', sort_order: 4 },
  { id: 'cat-5', name: 'Lainnya', slug: 'lainnya', color: '#6b7280', sort_order: 5 },
];

export const demoProducts = [
  {
    id: 'prod-1',
    title: 'Modul Ajar Matematika Kelas 1 SD Semester 1',
    slug: 'modul-ajar-matematika-kelas-1-sd-semester-1',
    description: 'Modul ajar lengkap matematika untuk kelas 1 SD semester 1. Berisi RPP, LKPD, media pembelajaran, dan asesmen.',
    type: 'free',
    sale_price: 0,
    original_price: null,
    stock_type: 'unlimited',
    stock_qty: null,
    badge: null,
    badge_custom: null,
    is_featured: false,
    cover_path: null,
    card_layout: 'compact',
    file_size: '2.4 MB',
    is_active: true,
    sort_order: 1,
    download_count: 128,
    category: demoCategories[0],
    category_id: 'cat-1',
  },
  {
    id: 'prod-2',
    title: 'ATP Bahasa Indonesia Kelas 2 SD Kurikulum Merdeka',
    slug: 'atp-bahasa-indonesia-kelas-2-sd',
    description: 'Alur Tujuan Pembelajaran Bahasa Indonesia kelas 2 SD fase A kurikulum merdeka.',
    type: 'free',
    sale_price: 0,
    original_price: null,
    stock_type: 'unlimited',
    stock_qty: null,
    badge: null,
    badge_custom: null,
    is_featured: false,
    cover_path: null,
    card_layout: 'square',
    file_size: '1.8 MB',
    is_active: true,
    sort_order: 2,
    download_count: 95,
    category: demoCategories[1],
    category_id: 'cat-2',
  },
  {
    id: 'prod-3',
    title: 'Media Pembelajaran Interaktif IPA Kelas 3 SD',
    slug: 'media-pembelajaran-ipa-kelas-3-sd',
    description: 'Media pembelajaran interaktif IPA untuk kelas 3 SD. Format PowerPoint + video animasi.',
    type: 'paid',
    sale_price: 35000,
    original_price: 50000,
    stock_type: 'limited',
    stock_qty: 25,
    badge: 'terlaris',
    badge_custom: null,
    is_featured: true,
    cover_path: null,
    card_layout: 'portrait',
    file_size: '15.2 MB',
    is_active: true,
    sort_order: 1,
    download_count: 312,
    category: demoCategories[2],
    category_id: 'cat-3',
  },
  {
    id: 'prod-4',
    title: 'Administrasi Guru Kelas 4 SD Full Tahun',
    slug: 'administrasi-guru-kelas-4-sd',
    description: 'Paket lengkap administrasi guru kelas 4 SD. Termasuk jurnal, absen, penilaian, dan laporan.',
    type: 'paid',
    sale_price: 45000,
    original_price: 65000,
    stock_type: 'unlimited',
    stock_qty: null,
    badge: 'diskon',
    badge_custom: null,
    is_featured: true,
    cover_path: null,
    card_layout: 'landscape',
    file_size: '8.5 MB',
    is_active: true,
    sort_order: 2,
    download_count: 450,
    category: demoCategories[3],
    category_id: 'cat-4',
  },
  {
    id: 'prod-5',
    title: 'Modul Ajar PKN Kelas 1 SD Semester 2',
    slug: 'modul-ajar-pkn-kelas-1-sd-semester-2',
    description: 'Modul ajar Pendidikan Kewarganegaraan untuk kelas 1 SD semester 2 kurikulum merdeka.',
    type: 'free',
    sale_price: 0,
    original_price: null,
    stock_type: 'unlimited',
    stock_qty: null,
    badge: null,
    badge_custom: null,
    is_featured: false,
    cover_path: null,
    card_layout: 'compact',
    file_size: '3.1 MB',
    is_active: true,
    sort_order: 3,
    download_count: 67,
    category: demoCategories[0],
    category_id: 'cat-1',
  },
  {
    id: 'prod-6',
    title: 'ATP Matematika Kelas 5 SD Fase C',
    slug: 'atp-matematika-kelas-5-sd-fase-c',
    description: 'Alur Tujuan Pembelajaran Matematika kelas 5 SD fase C kurikulum merdeka lengkap.',
    type: 'free',
    sale_price: 0,
    original_price: null,
    stock_type: 'unlimited',
    stock_qty: null,
    badge: 'baru',
    badge_custom: null,
    is_featured: false,
    cover_path: null,
    card_layout: 'square',
    file_size: '2.2 MB',
    is_active: true,
    sort_order: 4,
    download_count: 34,
    category: demoCategories[1],
    category_id: 'cat-2',
  },
  {
    id: 'prod-7',
    title: 'Template Sertifikat Kelulusan SD Customizable',
    slug: 'template-sertifikat-kelulusan-sd',
    description: 'Template sertifikat kelulusan SD yang bisa diedit. Format Canva + PowerPoint.',
    type: 'paid',
    sale_price: 25000,
    original_price: null,
    stock_type: 'limited',
    stock_qty: 50,
    badge: 'premium',
    badge_custom: null,
    is_featured: true,
    cover_path: null,
    card_layout: 'wide',
    file_size: '5.7 MB',
    is_active: true,
    sort_order: 3,
    download_count: 189,
    category: demoCategories[4],
    category_id: 'cat-5',
  },
  {
    id: 'prod-8',
    title: 'Bundle Media Pembelajaran SD Kelas 1-6',
    slug: 'bundle-media-pembelajaran-sd-kelas-1-6',
    description: 'Bundle lengkap media pembelajaran untuk semua kelas SD. Hemat 40%!',
    type: 'paid',
    sale_price: 125000,
    original_price: 210000,
    stock_type: 'limited',
    stock_qty: 10,
    badge: 'terlaris',
    badge_custom: null,
    is_featured: true,
    cover_path: null,
    card_layout: 'portrait',
    file_size: '45.0 MB',
    is_active: true,
    sort_order: 4,
    download_count: 567,
    category: demoCategories[2],
    category_id: 'cat-3',
  },
];

export const demoSections = [
  {
    id: 'sec-1',
    key: 'hero',
    label: 'Hero Section',
    is_visible: true,
    sort_order: 1,
    config: {
      title: 'Bantu Guru Yuk',
      subtitle: 'Download modul ajar, ATP, media pembelajaran gratis untuk guru SD Indonesia',
      cta_text: 'Lihat Produk Gratis',
      cta_url: '/free',
    },
  },
  {
    id: 'sec-2',
    key: 'featured_products',
    label: 'Produk Unggulan',
    is_visible: true,
    sort_order: 2,
    config: {},
  },
  {
    id: 'sec-3',
    key: 'categories',
    label: 'Kategori',
    is_visible: true,
    sort_order: 3,
    config: {},
  },
  {
    id: 'sec-4',
    key: 'free_products',
    label: 'Produk Gratis Terbaru',
    is_visible: true,
    sort_order: 4,
    config: {},
  },
  {
    id: 'sec-5',
    key: 'promo_banner',
    label: 'Banner Promo',
    is_visible: true,
    sort_order: 5,
    config: {
      text: 'Dapatkan bundle media pembelajaran SD dengan harga spesial! Hemat 40%',
      cta_text: 'Lihat Promo',
      cta_url: '/produk/bundle-media-pembelajaran-sd-kelas-1-6',
    },
  },
  {
    id: 'sec-6',
    key: 'about',
    label: 'Tentang BGY',
    is_visible: true,
    sort_order: 6,
    config: {
      title: 'Apa Itu Bantu Guru Yuk?',
      content: 'Bantu Guru Yuk adalah platform penyedia materi edukasi untuk guru SD Indonesia. Kami menyediakan modul ajar, ATP, media pembelajaran, dan administrasi sekolah secara gratis maupun berbayar. Semua materi dapat diunduh dengan mudah dan cepat.',
    },
  },
];

export const demoNavItems = [
  { id: 'nav-1', label: 'Home', target_type: 'external', target_url: '/', is_visible: true, sort_order: 1 },
  { id: 'nav-2', label: 'Gratis', target_type: 'external', target_url: '/free', is_visible: true, sort_order: 2 },
  { id: 'nav-3', label: 'Produk', target_type: 'external', target_url: '/produk', is_visible: true, sort_order: 3 },
];

export const demoSettings = {
  site_name: 'Bantu Guru Yuk',
  site_tagline: 'Toko Digital untuk Guru SD Indonesia',
  profile_name: 'Bantu Guru Yuk',
  profile_handle: '@bgy',
  profile_about: 'Toko digital guru — modul ajar, ATP, media pembelajaran untuk guru SD Indonesia.',
  profile_avatar_url: '',
  banner_url: '',
  banner_enabled: 'true',
  bg_color: '#0ea5a0',
  bg_style: 'gradient',
  social_links: JSON.stringify([
    { id: 'wa', platform: 'whatsapp', url: 'https://wa.me/6281234567890' },
    { id: 'tt', platform: 'tiktok', url: 'https://tiktok.com/@bantuguruyuk' },
    { id: 'ig', platform: 'instagram', url: 'https://instagram.com/bantuguruyuk' },
    { id: 'email', platform: 'email', url: 'mailto:hello@bantuguruyuk.web.id' },
  ]),
  theme_primary_color: '#0ea5a0',
  theme_secondary_color: '#0d7a8a',
  theme_border_radius: 'rounded',
  theme_font: 'Poppins',
  announcement_active: 'false',
  announcement_text: '📢 Gratis! Download Modul Ajar Matematika Kelas 1 SD Semester 1 untuk guru hebat!',
  announcement_url: '/free',
  announcement_bg_color: '#0ea5a0',
  announcement_text_color: '#ffffff',
};

export const demoFooterConfig = [
  { key: 'copyright_text', value: '© 2026 Bantu Guru Yuk. All rights reserved.' },
  { key: 'description', value: 'Bantu Guru Yuk adalah platform toko digital untuk guru SD Indonesia. Fokus ke materi siap pakai: modul ajar, ATP, media pembelajaran, dan administrasi sekolah.' },
];

// Kept for legacy admin pages (sidebar removed)
export const demoContacts = [
  { key: 'whatsapp', label: 'WhatsApp', value: '6281234567890' },
  { key: 'email', label: 'Email', value: 'hello@bantuguruyuk.web.id' },
];

export const demoFooterLinks = [];

