-- ============================================================
-- 011 — Security hardening
-- PREREQUISITE: SUPABASE_SERVICE_ROLE_KEY must be set in the deployment
-- environment. Checkout, voucher validation, the thank-you page and file
-- downloads now read/write through the service role on the server, so the
-- anon role no longer needs direct access to these tables/buckets.
-- ============================================================

-- 1. Vouchers: stop anon clients from listing every active voucher code.
DROP POLICY IF EXISTS "public can validate active vouchers" ON vouchers;

-- 2. Orders: only admins (and the server's service role, which bypasses RLS)
--    may touch orders. Removes any extra anon/public policies that may have
--    been added from the dashboard (they would expose buyer PII and allow
--    forging paid orders).
DO $$
DECLARE
  pol record;
BEGIN
  FOR pol IN
    SELECT policyname FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'orders' AND policyname <> 'admin all orders'
  LOOP
    RAISE NOTICE 'Dropping orders policy: %', pol.policyname;
    EXECUTE format('DROP POLICY %I ON orders', pol.policyname);
  END LOOP;
END $$;

-- 3. Paid product files: make the bucket private. Downloads are served via
--    short-lived signed URLs generated by /api/download and /api/download/free.
UPDATE storage.buckets SET public = false WHERE id = 'product-files';

DROP POLICY IF EXISTS "Public read store uploads" ON storage.objects;
CREATE POLICY "Public read store uploads" ON storage.objects
  FOR SELECT TO public
  USING (bucket_id = 'site-media');

-- 4. Uploads: only admins may write to storage buckets (was: any authenticated user).
DROP POLICY IF EXISTS "Authenticated upload store files" ON storage.objects;
CREATE POLICY "Authenticated upload store files" ON storage.objects
  FOR INSERT TO authenticated
  WITH CHECK (bucket_id IN ('site-media', 'product-files') AND is_admin());

-- 5. Reviews: reviewer e-mail is private; keep the "own review" policy from
--    matching anonymous users with a NULL e-mail.
DROP POLICY IF EXISTS "user_read_own_review" ON product_reviews;

-- 6. Products: RLS filters rows, not columns. Anonymous visitors must not be
--    able to read file_url / file_path of paid products through the public
--    REST API, so anon only gets the columns the storefront renders.
REVOKE SELECT ON products FROM anon;
GRANT SELECT (
  id, title, slug, description, category_id, type, purchase_button_label,
  sale_price, original_price, stock_type, stock_qty, badge, badge_custom,
  is_featured, cover_path, preview_path, file_size, card_layout, sort_order,
  is_active, published_at, deleted_at, created_at, meta_title, meta_desc,
  meta_description, download_count
) ON products TO anon;

NOTIFY pgrst, 'reload schema';
